user.create.table=CREATE TABLE IF NOT EXISTS "user"(id SERIAL PRIMARY KEY, name VARCHAR(50), last_name VARCHAR(50), age smallint)
user.drop.table=DROP TABLE IF EXISTS "user"
user.get.all=SELECT * FROM "user" limit ?
user.insert=INSERT INTO "user" (name, last_name, age) VALUES (?, ?, ?)
user.delete.by.id=DELETE FROM "user" WHERE id = ?
user.clean.table=DELETE FROM "user"